name: xshare
description: Lossless photo/video transfer over local network between iOS and Android
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  file_picker: ^8.1.4
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.1.1
  network_info_plus: ^6.1.1
  path_provider: ^2.1.3
  mime: ^1.0.5
  archive: ^3.6.1
  crypto: ^3.0.3
  open_filex: ^4.5.0
  http: ^1.2.2
  wakelock_plus: ^1.2.5
  wechat_assets_picker: ^9.7.0
  photo_manager: ^3.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true